### ISSUE TITLE
/installation/debian.md  存在矛盾

### ISSUE THREAD

**Issue by q2333gh** [v2rayA/v2raya.github.io#271]
如果没有启动vpn。很多下载操作在国内巨慢。
但是这个go.sh正是在设置vpn。

将下图关键词换为proxy 即issue主旨。
![image](https://github.com/v2rayA/v2raya.github.io/assets/32679742/4004f0fc-7bc7-4c95-a403-5e2c70ec9bec)

是否可以设置国内下载源，但是又不被封锁。

**Comment by q2333gh** [comment]
以10kb每秒下载文件，半个小时以后告知下载失败 ：）

**Comment by q2333gh** [comment]
我想办法手动下载了v2raycore的二进制 .zip包和v2raya的deb安装包。但是不会操作v2ray core关联到v2raya去， 使用单个ln -s命令链接v2raycore还不能运行

**Comment by mzz2017** [comment]
@q2333gh 你要放到 $PATH 去

**Comment by q2333gh** [comment]
另外我试过docker 运行v2raya容器，命令都输入正确，容器也在运行状态，就是无法进入localhost:2017 另外Ubuntu是全新裸金属安装的

**Comment by q2333gh** [comment]
整个流程下来网络问题太折磨了。我将探索一下境内有vmess地址的情况下如何一键下载和启动proxy

**Comment by MarksonHon** [comment]
> > @q2333gh 放到 /usr/bin/ 去
> > 嗯是的. 我是 这样操作了.
> 
> ```shell
> ln -s path/to/src/v2ray /usr/bin 
> ```
> 
> 但是v2raya网址 提示 geo.bat 啥的找不到.

因为光一个二进制是没用的，dat文件需要在 XDG_DATA_DIRS/v2ray 里面能够被找到

**Comment by q2333gh** [comment]
> > > @q2333gh 放到 /usr/bin/ 去
> > > 嗯是的. 我是 这样操作了.
> > 
> > 
> > ```shell
> > ln -s path/to/src/v2ray /usr/bin 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但是v2raya网址 提示 geo.bat 啥的找不到.
> 
> 因为光一个二进制是没用的，dat文件需要在 XDG_DATA_DIRS/v2ray 里面能够被找到
哦哦 ok.

所以这整个v2ray-core 的配置流程是啥? 我去读一读.sh配置脚本 或者是有文档吗?

**Comment by MarksonHon** [comment]
https://github.com/v2fly/fhs-install-v2ray/blob/master/install-release.sh

**Comment by mzz2017** [comment]
@q2333gh dat放到 /usr/share/v2ray/

**Comment by MarksonHon** [comment]
国内下载源目前不太可能直接提供，不过附带`v2ray`软件包的发行版（比如 Arch Linux、AOSC OS、NixOS 等）会方便得多

**Comment by q2333gh** [comment]
> 另外我试过docker 运行v2raya容器，命令都输入正确，容器也在运行状态，就是无法进入localhost:2017 另外Ubuntu是全新裸金属安装的

Docker的启动成功了.本来只需要一行命令安装docker. Docker官网我搞错了去装了docker desktop.来回三个站内网址跳转十多条指令. 

直接 apt install docker.io 一键安装.
docker 本身安装和拉取v2raya镜像都没有被墙.
proxy可以正常使用了!

**Comment by q2333gh** [comment]
这是安装脚本我上传了: 指令并不复杂.但是没有做很好的fault tolerance. 要自己盯着一点:

**Comment by q2333gh** [comment]
github提示无法上传.sh文件,自行复制命令到一个新的.sh文件并运行就好了.



```bash
#!/bin/bash

# install docker
apt update
apt upgrade
apt install docker.io -y

#download v2rayA image
docker pull mzz2017/v2raya

# run v2raya container
docker run -d \
  --restart=always \
  --privileged \
  --network=host \
  --name v2raya \
  -e V2RAYA_LOG_FILE=/tmp/v2raya.log \
  -v /lib/modules:/lib/modules:ro \
  -v /etc/resolv.conf:/etc/resolv.conf \
  -v /etc/v2raya:/etc/v2raya \
  mzz2017/v2raya

#show status of containers
docker ps -a 

```

**Comment by MarksonHon** [comment]
镜像站的问题已经修好了，现在应该能正常下载核心，也可能用新的脚本安装：
```sh
sudo sh -c "$(wget -qO- https://hubmirror.v2raya.org/v2rayA/v2rayA-installer/raw/main/installer.sh)" @ --with-v2ray
```
