### ISSUE TITLE
参照https://v2raya.org/en/docs/prologue/installation/debian/操作ubuntu20安装报错

### ISSUE THREAD

**Issue by keeper-jie** [v2rayA/v2raya.github.io#286]
## Description

Ubuntu20执行命令
‘‘‘echo "deb [signed-by=/etc/apt/keyrings/v2raya.asc] https://apt.v2raya.org/ v2raya main" | sudo tee /etc/apt/sources.list.d/v2raya.list
sudo apt update‘‘’
报错
```
(base) jie@jie-MS-7D30:~$ sudo apt update
Hit:1 http://mirrors.aliyun.com/ubuntu focal InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu focal-security InRelease
Hit:3 http://mirrors.aliyun.com/ubuntu focal-updates InRelease
Hit:4 http://mirrors.aliyun.com/ubuntu focal-proposed InRelease
Hit:5 http://mirrors.aliyun.com/ubuntu focal-backports InRelease
Hit:6 https://nvidia.github.io/libnvidia-container/stable/deb/amd64  InRelease
Get:7 https://apt.v2raya.org v2raya InRelease [9,794 B]
Err:7 https://apt.v2raya.org v2raya InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 354E516D494EF95F
Reading package lists... Done
W: GPG error: https://apt.v2raya.org v2raya InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 354E516D494EF95F
E: The repository 'https://apt.v2raya.org v2raya InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
我试了一下，https://apt.v2raya.org/ 不可访问，可能是这部分的问题

### Steps to reproduce

使用Ubuntu20进行操作

### Expected result

可以更新软件列表并安装软件

### Actual result

报错

### Environment

Ubuntu20

**Comment by MarksonHon** [comment]
1. 网站托管在 GitHub，GitHub 目前没报什么错误，不过国内的确不一定能访问
2.  仔细看文档，你漏掉了一个步骤

**Comment by keeper-jie** [comment]
参照网站 https://www.scczz.com/953.html 能正常安装使用

但是连接节点的时候报错`failed to connect: failed to connect: geoip.dat or geosite.dat file does not exists`

**Comment by MarksonHon** [comment]
所以你有看文档本身么？你这像是没装`v2ray`这个包

**Comment by keeper-jie** [comment]
抱歉，我仔细查看了一下官网文档 https://v2raya.org/docs/prologue/installation/debian/ ，原因是我直接把两个命令复制扔到terminal中报的错误，还有就是有`sudo apt install v2raya v2ray ## 也可以使用 xray 包`，这里我把注释也扔到terminal中所以报的错误，这个issue可以留在这里提醒后来的人，命令一行一行复制运行，命令后面的#内容不要复制

谢谢你的耐心解答和这个这么棒的项目，之前都是用windows的v2rayN直接测速然后回车选节点，linux上我参考project V，有一个简易的版本需要修改配置文件，然后就找到你这个Web版本的，非常感谢有订阅的功能，不用一个个导出复制了，和windows上逻辑一致
